/*
===================================================================================
DDL Script: Create Gold Views
===================================================================================
Script Purpose:
	This script creates views for the Gold layer in the data warehouse.
	The Gold layer represents the final dimension and fact tables (Star Schema)

	Each view performs transformations and combines data from the Silver layer
	to produce a clean, enriched and business-ready dataset.

Usage:
	-These views can be queried directly for analytics and reporting.
===================================================================================
*/

--CREATING CUSTOMER DIMENSION VIEW
--=====================================================================
--Checking the duplicates after joining tables
Select cst_id,count(*) from
	(Select
		ci.cst_id,
		ci.cst_key,
		ci.cst_firstname,
		ci.cst_lastname,
		ci.cst_material_status,
		CASE WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr --CRM is the master for gender info
	         ELSE COALESCE(ca.gen,'n/a') --this function will take non-null value
		END AS new_cst_gen, --This column has more info then source crm and source erp
		ci.cst_create_date,
		ca.bdate,
		cl.cntry
	from silver.crm_cust_info as ci
	LEFT JOIN silver.erp_cust_az12 as ca
	ON ci.cst_key = ca.cid
	LEFT JOIN silver.erp_loc_a101 as cl
	ON ci.cst_key = cl.cid) t
GROUP BY cst_id
HAVING count(*)>1



--but for gender info crm and erp tables both has gender info columns. first check distinct values from both columns
Select DISTINCT
	ci.cst_gndr,
	ca.gen
from silver.crm_cust_info as ci
	LEFT JOIN silver.erp_cust_az12 as ca
	ON ci.cst_key = ca.cid
	LEFT JOIN silver.erp_loc_a101 as cl
	ON ci.cst_key = cl.cid
ORDER BY 1,2
--so after looking values from above join, it is found that values from both columns are not matching and in that case we need to check which table is master table or which source provide exact information i.e. crm or erp. Wherever NULL value is present it means the value was not found in the right table and so NULL value was returned. In that case we will use COALESCE function to avoid NULL populating in GOLD layer
--So we are considering correct information is provided by crm source, and value from that will be considered as final information. And if crm source has no value then it will take from erp source.
--This step of integrating values from both the tables is known as DATA INTEGRATION
Select DISTINCT
	ci.cst_gndr,
	ca.gen,
	CASE WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr --CRM is the master for gender info
	     ELSE COALESCE(ca.gen,'n/a') --this function will take non-null value
	END AS new_cst_gen --This column has more info then source crm and source erp
from silver.crm_cust_info as ci
	LEFT JOIN silver.erp_cust_az12 as ca
	ON ci.cst_key = ca.cid
	LEFT JOIN silver.erp_loc_a101 as cl
	ON ci.cst_key = cl.cid
ORDER BY 1,2


--now next step is renaming columns to friendly and meaningful names. Also order the columns in logical groups to improve readability
Select
	ci.cst_id as customer_id,
	ci.cst_key as customer_number,
	ci.cst_firstname as first_name,
	ci.cst_lastname as last_name,
	ca.bdate as birthdate,
	cl.cntry as country,
	ci.cst_material_status as marital_status,
	CASE WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr --CRM is the master for gender info
         ELSE COALESCE(ca.gen,'n/a') --this function will take non-null value
	END AS gender, --This column has more info then source crm and source erp
	ci.cst_create_date as create_date
from silver.crm_cust_info as ci
LEFT JOIN silver.erp_cust_az12 as ca
ON ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 as cl
ON ci.cst_key = cl.cid

--As this is a dimension so we will create a primary key
--Sometimes we do not get columns with primary key, in that case we can generate the primary key from columns in the table using row_number function. It is said as surrogate key
Select
	ROW_NUMBER() OVER(ORDER BY cst_id) AS customer_key, --primary/surrogate key generated by us and system assigns based on condition given by us
	ci.cst_id as customer_id,
	ci.cst_key as customer_number,
	ci.cst_firstname as first_name,
	ci.cst_lastname as last_name,
	ca.bdate as birthdate,
	cl.cntry as country,
	ci.cst_material_status as marital_status,
	CASE WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr --CRM is the master for gender info
         ELSE COALESCE(ca.gen,'n/a') --this function will take non-null value
	END AS gender, --This column has more info then source crm and source erp
	ci.cst_create_date as create_date
from silver.crm_cust_info as ci
LEFT JOIN silver.erp_cust_az12 as ca
ON ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 as cl
ON ci.cst_key = cl.cid



--As we will not create table in gold layer and we will create view
--CREATING DIM_CUSTOMER VIEW
--====================================================================
IF OBJECT_ID('gold.dim_customers','V') IS NOT NULL
	DROP VIEW gold.dim_customers;
GO

CREATE VIEW gold.dim_customers AS
Select
	ROW_NUMBER() OVER(ORDER BY cst_id) AS customer_key, --primary/surrogate key generated by us and system assigns based on condition given by us
	ci.cst_id as customer_id,
	ci.cst_key as customer_number,
	ci.cst_firstname as first_name,
	ci.cst_lastname as last_name,
	ca.bdate as birthdate,
	cl.cntry as country,
	ci.cst_material_status as marital_status,
	CASE WHEN ci.cst_gndr != 'n/a' THEN ci.cst_gndr --CRM is the master for gender info
         ELSE COALESCE(ca.gen,'n/a') --this function will take non-null value
	END AS gender, --This column has more info then source crm and source erp
	ci.cst_create_date as create_date
from silver.crm_cust_info as ci
LEFT JOIN silver.erp_cust_az12 as ca
ON ci.cst_key = ca.cid
LEFT JOIN silver.erp_loc_a101 as cl
ON ci.cst_key = cl.cid




--CREATING PRODUCTS DIMENSION VIEW
--=====================================================================
Select * from silver.crm_prd_info
Select * from silver.erp_px_cat_g1v2

--we will take only current info and not historical info, this can be identified from prd_end_dt
Select
	pi.prd_id,
	pi.cat_id,
	pi.prd_key,
	pi.prd_nm,
	pc.cat,
	pc.subcat,
	pc.maintenance,
	pi.prd_cost,
	pi.prd_line,
	pi.prd_start_dt
from silver.crm_prd_info AS pi
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
ON pi.cat_id = pc.id
where pi.prd_end_dt is null --GET only current data and filtering out historical data

--After joining the tables, wherever NULL is populated those is updated with n/a
Select
	pi.prd_id,
	pi.cat_id,
	pi.prd_key,
	pi.prd_nm,
	CASE WHEN pc.cat IS NOT NULL THEN pc.cat 
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS new_cat,
	CASE WHEN pc.subcat IS NOT NULL THEN pc.subcat
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS new_subcat,
	CASE WHEN pc.maintenance IS NOT NULL THEN pc.maintenance
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS new_maintenance,
	pi.prd_cost,
	pi.prd_line,
	pi.prd_start_dt
from silver.crm_prd_info AS pi
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
ON pi.cat_id = pc.id
where pi.prd_end_dt is null

--checking duplicates, no duplicates should be there
Select prd_key, count(*) from
(Select
	pi.prd_id,
	pi.cat_id,
	pi.prd_key,
	pi.prd_nm,
	CASE WHEN pc.cat IS NOT NULL THEN pc.cat 
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS new_cat,
	CASE WHEN pc.subcat IS NOT NULL THEN pc.subcat
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS new_subcat,
	CASE WHEN pc.maintenance IS NOT NULL THEN pc.maintenance
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS new_maintenance,
	pi.prd_cost,
	pi.prd_line,
	pi.prd_start_dt
from silver.crm_prd_info AS pi
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
ON pi.cat_id = pc.id
where pi.prd_end_dt is null) t
GROUP BY prd_key
HAVING count(*) > 1


--ordering the columns in logical groups to improve readability
Select
	pi.prd_id AS product_id,
	pi.prd_key AS product_number,
	pi.prd_nm AS product_name,
	pi.cat_id AS category_id,
	CASE WHEN pc.cat IS NOT NULL THEN pc.cat 
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS category,
	CASE WHEN pc.subcat IS NOT NULL THEN pc.subcat
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS subcategory,
	CASE WHEN pc.maintenance IS NOT NULL THEN pc.maintenance
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS maintenance,
	pi.prd_cost AS cost,
	pi.prd_line AS product_line,
	pi.prd_start_dt AS start_date
from silver.crm_prd_info AS pi
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
ON pi.cat_id = pc.id
where pi.prd_end_dt is null --filtering out all historical data



--This is a dimension, so we need to create primary key
Select
	ROW_NUMBER() OVER (ORDER BY pi.prd_start_dt, pi.prd_key) AS product_key,
	pi.prd_id AS product_id,
	pi.prd_key AS product_number,
	pi.prd_nm AS product_name,
	pi.cat_id AS category_id,
	CASE WHEN pc.cat IS NOT NULL THEN pc.cat 
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS category,
	CASE WHEN pc.subcat IS NOT NULL THEN pc.subcat
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS subcategory,
	CASE WHEN pc.maintenance IS NOT NULL THEN pc.maintenance
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS maintenance,
	pi.prd_cost AS cost,
	pi.prd_line AS product_line,
	pi.prd_start_dt AS start_date
from silver.crm_prd_info AS pi
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
ON pi.cat_id = pc.id
where pi.prd_end_dt is null --filtering out all historical data

--CREATING DIM_PRODUCTS VIEW
--==============================================================
IF OBJECT_ID('gold.dim_products','V') IS NOT NULL
	DROP VIEW gold.dim_products;
GO

CREATE VIEW gold.dim_products AS
Select
	ROW_NUMBER() OVER (ORDER BY pi.prd_start_dt, pi.prd_key) AS product_key,
	pi.prd_id AS product_id,
	pi.prd_key AS product_number,
	pi.prd_nm AS product_name,
	pi.cat_id AS category_id,
	CASE WHEN pc.cat IS NOT NULL THEN pc.cat 
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS category,
	CASE WHEN pc.subcat IS NOT NULL THEN pc.subcat
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS subcategory,
	CASE WHEN pc.maintenance IS NOT NULL THEN pc.maintenance
		 ELSE 'n/a' --modifying the values with n/a if NULL is found
	END AS maintenance,
	pi.prd_cost AS cost,
	pi.prd_line AS product_line,
	pi.prd_start_dt AS start_date
from silver.crm_prd_info AS pi
LEFT JOIN silver.erp_px_cat_g1v2 AS pc
ON pi.cat_id = pc.id
where pi.prd_end_dt is null --filtering out all historical data



--CREATING SALES FACT VIEW
--=====================================================================
Select * from silver.crm_sales_details;
--we will be connecting fact table to dimensions table using surrogate key from dimensions table
--here sls_prd_key and sls_cust_id will be taken using surrogate key(product_key, customer_key) from gold dimensions view of customers and products
Select
	sd.sls_ord_num,
	pr.product_key,
	cm.customer_key,
	sd.sls_order_dt,
	sd.sls_ship_dt,
	sd.sls_due_dt,
	sd.sls_sales,
	sd.sls_quantity,
	sd.sls_price
from silver.crm_sales_details AS sd
LEFT JOIN gold.dim_customers as cm
ON sd.sls_cust_id = cm.customer_id
LEFT JOIN gold.dim_products AS pr
ON sd.sls_prd_key = pr.product_number

--renaming the columns and ordering in logical groups
Select
	sd.sls_ord_num AS order_number,
	pr.product_key,
	cm.customer_key,
	sd.sls_order_dt AS order_date,
	sd.sls_ship_dt AS shipping_date,
	sd.sls_due_dt AS due_date,
	sd.sls_sales AS sales_amount,
	sd.sls_quantity AS sales_quantity,
	sd.sls_price AS price
from silver.crm_sales_details AS sd
LEFT JOIN gold.dim_customers as cm
ON sd.sls_cust_id = cm.customer_id
LEFT JOIN gold.dim_products AS pr
ON sd.sls_prd_key = pr.product_number

--CREATING FACT_SALES VIEW
--=============================================================

IF OBJECT_ID('gold.fact_sales','V') IS NOT NULL
	DROP gold.fact_sales;
GO

CREATE VIEW gold.fact_sales AS
Select
	sd.sls_ord_num AS order_number,
	pr.product_key,
	cm.customer_key,
	sd.sls_order_dt AS order_date,
	sd.sls_ship_dt AS shipping_date,
	sd.sls_due_dt AS due_date,
	sd.sls_sales AS sales_amount,
	sd.sls_quantity AS sales_quantity,
	sd.sls_price AS price
from silver.crm_sales_details AS sd
LEFT JOIN gold.dim_customers as cm
ON sd.sls_cust_id = cm.customer_id
LEFT JOIN gold.dim_products AS pr
ON sd.sls_prd_key = pr.product_number
